name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Format using Prettier
      uses: creyD/prettier_action@v3.1
      with:
        prettier_options: --write **/*.{html,js,md,scss}

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2.4.13
      with:
        hugo-version: 'latest'
        extended: true

    - name: Install Yarn dependencies
      uses: borales/actions-yarn@v2.3.0

    - name: Build site with Hugo
      run: hugo --minify --buildFuture

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_dir: ./public
        publish_branch: master
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: arzg/arzg.github.io
